### ISSUE TITLE
Blob URL Support

### ISSUE THREAD

**Issue by dhpanteon** [ajithvgiri/PDF-Downloader#1]
Dose this download blob URL ?

**Comment by ShakeebM** [comment]
Sorry it doesn't support blob url

**Comment by dhpanteon** [comment]
refer this link 
https://superuser.com/questions/948738/what-is-the-blobhttp-prefix-and-where-can-i-learn-more-about-this

**Comment by dhpanteon** [comment]
Refer this link to add support 
https://stackoverflow.com/questions/48892390/download-blob-file-from-website-inside-android-webviewclient/48954970#48954970
